import React, { useState } from 'react';
import { InfinityScene } from './components/InfinityScene';
import { TechniqueType } from './types';
import { ChevronRight, Sun, Moon } from 'lucide-react';

const App = () => {
  const [currentTechnique, setCurrentTechnique] = useState<TechniqueType>(TechniqueType.NEUTRAL);
  const [theme, setTheme] = useState<'dark' | 'light'>('dark');

  const techniques = [
    { 
      type: TechniqueType.NEUTRAL, 
      label: 'Infinity', 
      subtitle: 'The Neutral Limitless',
      color: 'border-white/20',
      activeColor: 'bg-slate-800 text-white border-slate-600',
      activeColorLight: 'bg-white text-slate-900 border-slate-300 shadow-md',
      details: {
        concept: "Convergence of an Infinite Series",
        space: "Divides the space between Gojo and any approaching object infinitely. It brings the mathematical paradox of 'Achilles and the Tortoise' into reality.",
        speed: "As an object approaches the barrier, its relative speed is reduced exponentially, creating the illusion that it has stopped completely.",
        implication: "No attack can ever reach him. He is untouchable, separated by an infinite distance contained within a finite space."
      }
    },
    { 
      type: TechniqueType.BLUE, 
      label: 'Lapse: Blue', 
      subtitle: 'Cursed Technique Lapse',
      color: 'border-sky-500/20',
      activeColor: 'bg-sky-900/40 text-sky-400 border-sky-500/50',
      activeColorLight: 'bg-sky-50 text-sky-700 border-sky-200 shadow-md',
      details: {
        concept: "Negative Distance",
        space: "By amplifying the Limitless numbers, Gojo creates a situation where 'negative distance' exists. The universe attempts to correct this anomaly by filling the vacuum.",
        speed: "Creates a powerful attractive force. Matter is pulled violently towards the center of the anomaly to fill the empty space.",
        implication: "Can be used for high-speed movement (teleportation-like speed) or to crush enemies by imploding the space around them."
      }
    },
    { 
      type: TechniqueType.RED, 
      label: 'Reversal: Red', 
      subtitle: 'Cursed Technique Reversal',
      color: 'border-red-500/20',
      activeColor: 'bg-red-900/40 text-red-400 border-red-500/50',
      activeColorLight: 'bg-red-50 text-red-700 border-red-200 shadow-md',
      details: {
        concept: "Positive Distance",
        space: "Generated by flowing positive energy (Reverse Cursed Technique) into the Limitless. It inverts the effect of Blue, creating a divergence of space.",
        speed: "Generates an extremely violent repulsive force. Instead of pulling in, it blasts everything away with immense speed and power.",
        implication: "More destructive than Blue. It creates a shockwave that repels all matter, clearing vast areas instantly."
      }
    },
    { 
      type: TechniqueType.PURPLE, 
      label: 'Hollow: Purple', 
      subtitle: 'Hollow Technique',
      color: 'border-purple-500/20',
      activeColor: 'bg-purple-900/40 text-purple-400 border-purple-500/50',
      activeColorLight: 'bg-purple-50 text-purple-700 border-purple-200 shadow-md',
      details: {
        concept: "Imaginary Mass",
        space: "Combines the attraction of Blue and the repulsion of Red. The collision of these two infinities creates an imaginary mass that defies standard physics.",
        speed: "Moves instantaneously, erasing everything in its path at the atomic level.",
        implication: "The ultimate destructive technique. It doesn't just hit; it removes existence from reality."
      }
    },
  ];

  const activeTech = techniques.find(t => t.type === currentTechnique) || techniques[0];

  const toggleTheme = () => {
    setTheme(prev => prev === 'dark' ? 'light' : 'dark');
  };

  const isDark = theme === 'dark';

  return (
    <div className={`flex w-full h-screen overflow-hidden transition-colors duration-500 font-sans ${isDark ? 'bg-gojo-dark text-white' : 'bg-slate-50 text-slate-900'}`}>
      
      {/* LEFT PANEL: Information & Controls */}
      <div className={`w-[400px] lg:w-[450px] flex flex-col z-20 shadow-2xl overflow-hidden border-r transition-colors duration-500 ${isDark ? 'bg-slate-900/90 border-slate-800' : 'bg-white border-slate-200'}`}>
        
        {/* Header */}
        <div className={`p-8 pb-4 border-b ${isDark ? 'border-slate-800' : 'border-slate-100'}`}>
           <div className="flex justify-between items-start mb-2">
             <h1 className="text-4xl font-bold tracking-tight font-serif">LIMITLESS</h1>
             <button 
               onClick={toggleTheme}
               className={`p-2 rounded-full transition-colors ${isDark ? 'bg-slate-800 hover:bg-slate-700 text-yellow-400' : 'bg-slate-100 hover:bg-slate-200 text-slate-600'}`}
             >
               {isDark ? <Sun size={20} /> : <Moon size={20} />}
             </button>
           </div>
           <div className={`h-1 w-12 mb-4 ${isDark ? 'bg-white/30' : 'bg-slate-800'}`}></div>
           <p className={`text-sm font-serif uppercase tracking-widest ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
             Inherited Technique // Gojo Clan
           </p>
        </div>

        {/* Scrollable Content Area */}
        <div className="flex-1 overflow-y-auto custom-scrollbar p-6 space-y-8">
          
          {/* Technique Selectors */}
          <div className="space-y-3">
             <h2 className={`text-xs font-serif font-bold uppercase tracking-widest mb-4 ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>Select Technique</h2>
             {techniques.map((tech) => (
              <button
                key={tech.label}
                onClick={() => setCurrentTechnique(tech.type)}
                className={`
                  group relative w-full text-left p-4 rounded-none border-l-2 transition-all duration-300
                  ${currentTechnique === tech.type 
                    ? (isDark ? 'border-gojo-blue bg-slate-800/50' : 'border-slate-900 bg-slate-100')
                    : (isDark ? 'border-transparent hover:bg-slate-800/30' : 'border-transparent hover:bg-slate-50')}
                `}
              >
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className={`text-lg font-serif font-bold tracking-wide ${currentTechnique === tech.type ? '' : (isDark ? 'text-slate-400' : 'text-slate-600')}`}>
                      {tech.label}
                    </h3>
                    <p className={`text-[10px] mt-1 font-sans uppercase tracking-wider ${currentTechnique === tech.type ? 'opacity-80' : 'text-slate-500'}`}>
                      {tech.subtitle}
                    </p>
                  </div>
                  {currentTechnique === tech.type && (
                    <ChevronRight size={16} className="animate-pulse opacity-70" />
                  )}
                </div>
              </button>
            ))}
          </div>

          {/* Explanation Section */}
          <div className={`mt-4 pt-6 border-t ${isDark ? 'border-slate-800' : 'border-slate-200'}`}>
             <h2 className={`text-xs font-serif font-bold uppercase tracking-widest mb-6 ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>Analysis: {activeTech.label}</h2>
             
             <div className="space-y-8">
                <div className="group">
                  <h3 className={`text-sm font-serif font-bold uppercase tracking-wider mb-2 flex items-center gap-2 ${isDark ? 'text-slate-200' : 'text-slate-800'}`}>
                    Concept
                  </h3>
                  <p className={`text-sm leading-relaxed pl-4 border-l transition-colors ${isDark ? 'text-slate-400 border-slate-700' : 'text-slate-600 border-slate-300'}`}>
                    {activeTech.details.concept}
                  </p>
                </div>

                <div className="group">
                  <h3 className={`text-sm font-serif font-bold uppercase tracking-wider mb-2 flex items-center gap-2 ${isDark ? 'text-slate-200' : 'text-slate-800'}`}>
                    Spatial Manipulation
                  </h3>
                  <p className={`text-sm leading-relaxed pl-4 border-l transition-colors ${isDark ? 'text-slate-400 border-slate-700' : 'text-slate-600 border-slate-300'}`}>
                    {activeTech.details.space}
                  </p>
                </div>

                <div className="group">
                  <h3 className={`text-sm font-serif font-bold uppercase tracking-wider mb-2 flex items-center gap-2 ${isDark ? 'text-slate-200' : 'text-slate-800'}`}>
                    Velocity & Mass
                  </h3>
                  <p className={`text-sm leading-relaxed pl-4 border-l transition-colors ${isDark ? 'text-slate-400 border-slate-700' : 'text-slate-600 border-slate-300'}`}>
                    {activeTech.details.speed}
                  </p>
                </div>

                <div className="group">
                  <h3 className={`text-sm font-serif font-bold uppercase tracking-wider mb-2 flex items-center gap-2 ${isDark ? 'text-slate-200' : 'text-slate-800'}`}>
                    Combat Implications
                  </h3>
                  <p className={`text-sm leading-relaxed pl-4 border-l transition-colors ${isDark ? 'text-slate-400 border-slate-700' : 'text-slate-600 border-slate-300'}`}>
                    {activeTech.details.implication}
                  </p>
                </div>
             </div>
          </div>
        </div>
      </div>

      {/* RIGHT PANEL: Simulation */}
      <div className="flex-1 relative bg-black/5">
        <InfinityScene 
          technique={currentTechnique} 
          isAttacking={true} 
          onImpact={() => {}} 
          theme={theme}
        />
        
        <div className={`absolute bottom-8 right-8 pointer-events-none text-xs font-serif uppercase tracking-[0.2em] opacity-50 ${isDark ? 'text-white' : 'text-slate-900'}`}>
           Sorcery Simulation V.2.0
        </div>
      </div>
    </div>
  );
};

export default App;